### PR TITLE
extended-shown unbound from button_extended.active

### PR DESCRIPTION
**Pull request by DSroD**
This PR is a proposal for a fix of #182 - `extended-shown` settings value is no longer bound to the state but rather loaded on construction of a new window and set when changed. This results in following behaviour
- When user toggles extended functionality on in any open window, `extended-shown` is set to true, however no other instance inherits this action. Newly opened windows of app will have extended functionalities shown as this setting is loaded on construction
- Same applies when user toggles it off in any open window

### CODE REVIEW

**Comment by jeremypw** [comment]
I think you should be able to get the same behaviour just by using different SettingsBindFlags.  
Maybe `SettingsBindFlags.DEFAULT | SettingsBindFlags.GET_NO_CHANGES`?

**Comment by DSroD** [comment]
Yes, you are right, adding `GET_NO_CHANGES` to flags leads to the same behaviour. Latest commit removes my previous changes and modifies the SettingsBindFlags.

**Comment by jeremypw** [comment]
We usually omit the `GLib` namespace unless to do so would lead to an ambiguity.

**Comment by DSroD** [comment]
I decided to include it as it was present in the bind flags before the changes. However I forgot to add it to the second flag *(note to myself: do not write code on bus again)*

**Review by jeremypw — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
