### PR TITLE
Initial prototype for fractions

### LINKED ISSUE #114: Also show common fractions
Not sure how easy this is, but a super handy addition to the Calculator on Android is showing common fractions for results. So if you calculate 42÷16, it shows:

Android screenshot

This is incredibly nice with our stupid Imperial measurements, and can also just be a nice nudge for “oh yeah that's ⅝, that makes sense.”

### PR DESCRIPTION
**Pull request by cassidyjames**
To fix #114 

image

- [ ] Figure out actual design
- [ ] Probably use custom styling instead of Unicode fraction characters (so it can be arbitrary fractions)
- [ ] Put fraction label in revealer
- [ ] Hook up to real logic (you know, the hard part)

### CODE REVIEW

**Comment by fitojb** [comment]
Arbitrary fractions can be made by just using U+2044 FRACTION SLASH; this will work with almost all modern OpenType UI fonts, incl. Inter.

**Comment by cassidyjames** [comment]
@fitojb we're not using Inter in elementary OS, we use Open Sans. And it appears that unicode character is not enough, at least with Open Sans: we have to use Pango to size and position the numerator and denominator.

**Comment by jeremypw** [comment]
@cassidyjames This branch contains an algorithm for calculating the nearest fraction for the result:

https://github.com/elementary/calculator/tree/show-as-fraction

It shows the fraction as a tooltip pending UI design.  Please take from this branch if you need to.

**Comment by jeremypw** [comment]
`show-as-fraction` branch now works for negatives.  Does not reduce fraction if error > 10% (adjustable).

**Pull request closed without merging**
