### PR TITLE
Changed HeaderBar Style to Granite.STYLE_CLASS_FLAT

### PR DESCRIPTION
**Pull request by Chandram-Dutta**
New Header Bar
Calculator

### CODE REVIEW

**Comment by jeremypw** [comment]
As this is not linked to an existing issue, needs UX team comment.

**Comment by jeremypw** [comment]
@Chandram-Dutta Could you add your reason for proposing this UI change?

**Comment by Chandram-Dutta** [comment]
> @Chandram-Dutta Could you add your reason for proposing this UI change?

The reason behind this is that
1) It's a refreshing change in design.
2) Most applets & apps that cannot be resized now have the flat design.
3) The new apps built for elementary follow this design trend(tasks app) so this is an inevitable change.

**Review by danirabbit — APPROVED** [review]
LFG :rocket:

**Pull request merged**
