### PR TITLE
Make headerbar match all system apps

### PR DESCRIPTION
**Pull request by BAProductions**
- Switch from Gtk.HeaderBar --> Hdy.HeaderBar.
- Add close button Hdy.HeaderBar.
- Add missing headerbar.show_all ().

### CODE REVIEW

**Comment by lenemter** [comment]
Handy is GTK 3 library and Calculator is GTK 4 app. We now have Adwaita in GTK 4, however new header bar is not needed here. Also AFAIK we no longer need `show_all` in GTK 4.

**Comment by BAProductions** [comment]
Screenshot from 2023-03-05 21-35-17
Screenshot from 2023-03-05 21-38-47

**Comment by BAProductions** [comment]
> Handy is GTK 3 library and Calculator is GTK 4 app. We now have Adwaita in GTK 4, however new header bar is not needed here. Also AFAIK we no longer need `show_all` in GTK 4.

Hold on I need to test this on my Eos 7 MV.

**Comment by BAProductions** [comment]
> eOS7 System Calculator built from source
That I get, But it still need to respect mt theme header bar at most.

**Pull request closed without merging**
