### PR TITLE
Change naming from 'org.pantheon'

### PR DESCRIPTION
**Pull request by mdh34**
Changes naming to `com.github.elementary` as per #2

### CODE REVIEW

**Comment by mdh34** [comment]
according to #2 "we should switch to using io.elementary for shell/OS components, and com.github.elementary for first-party apps" - does the calculator count as an OS component, or a first-party app?

**Comment by tintou** [comment]
There is a comment in this bug report suggesting another scheme, it's just that the main bug hasn't been edited

**Comment by mdh34** [comment]
Ah OK, I'll change it :)

**Comment by danrabbit** [comment]
Marking as `blocked` since this will remove the icon from the dock for anyone that has pinned it. It will need a patch in packaging to prevent that from happening on Loki

**Pull request merged**
