### PR TITLE
MainWindow: Force elementary style

### PR DESCRIPTION
**Pull request by cassidyjames**
This fixes the Flatpak when using a non-elementary(-greenfield) stylesheet by forcing the elementary stylesheet from the platform, but still allows accent colors if you're using the elementary stylesheet.

Test by setting your system stylesheet to Adwaita, or by running the Flatpak on elementary OS 5.

### CODE REVIEW

**Comment by cassidyjames** [comment]
Also, if we're gonna want to do this in every app, is it worth shortening to a one-liner so we don't have to maintain the prefix const in several places?

**Comment by cassidyjames** [comment]
Now depends on https://github.com/elementary/granite/pull/486

**Comment by danrabbit** [comment]
You'll need to bump granite dep to 6.1.0 since we already released 6.0

**Comment by cassidyjames** [comment]
@danrabbit it looks like Flatpak CI is still failing because Granite 6.1 isn't available there. Do we need to release Granite, or just wait for the Flatpak platform to rebuild?

**Comment by danrabbit** [comment]
We would need to release a new granite since the platform is pull the 6 release tag

**Comment by cassidyjames** [comment]
We don't want to handle this in apps

**Pull request closed without merging**
